import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.way2automation.com/way2auto_jquery/index.php');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('name');
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="phone"]').fill('0987654321');
  await page.locator('input[name="phone"]').press('Tab');
  await page.locator('input[name="email"]').fill('someemail12@gmail.com');
  await page.locator('input[name="email"]').press('Tab');
  await page.locator('input[name="city"]').click();
  await page.locator('input[name="city"]').fill('Bangalore');
  await page.locator('input[name="city"]').press('Tab');
  await page.locator('#load_box input[name="username"]').fill('someusername');
  await page.locator('#load_box input[name="username"]').press('Tab');
  await page.locator('#load_box input[name="password"]').fill('password@123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.waitForTimeout(8000);
  await page.getByRole('link', { name: 'ENTER TO THE TESTING WEBSITE' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Registration' }).click();
  const page1 = await page1Promise;
  await page1.locator('#register_form input[name="name"]').click();
  await page1.locator('#register_form input[name="name"]').fill('first');
  await page1.locator('#register_form input[name="name"]').press('Tab');
  await page1.getByRole('paragraph').filter({ hasText: 'Last Name:' }).getByRole('textbox').fill('last');
  await page1.getByText('Married').click();
  await page1.getByText('Reading').click();
  await page1.getByRole('group').filter({ hasText: 'Country: India India' }).getByRole('combobox').selectOption('India');
  await page1.locator('#register_form div').filter({ hasText: 'Month 1' }).getByRole('combobox').selectOption('1');
  await page1.locator('#register_form div').filter({ hasText: 'Day 1' }).getByRole('combobox').selectOption('1');
  await page1.locator('#register_form div').filter({ hasText: 'Year 2014' }).getByRole('combobox').selectOption('2014');
  await page1.locator('#register_form input[name="phone"]').click();
  await page1.locator('#register_form input[name="phone"]').fill('0987654321');
  await page1.locator('#register_form input[name="username"]').click();
  await page1.locator('#register_form input[name="username"]').fill('someid123');
  await page1.locator('#register_form input[name="username"]').press('Tab');
  await page1.locator('#register_form input[name="email"]').fill('someemail123@gmail.com');
  await page1.locator('#register_form input[name="email"]').press('Tab');
  await page1.locator('input[type="file"]').press('Tab');
  await page1.locator('textarea').fill('some random text');
  await page1.locator('textarea').press('Tab');
  await page1.locator('#register_form input[name="password"]').fill('password@123');
  await page1.locator('#register_form input[name="password"]').press('Tab');
  await page1.locator('input[name="c_password"]').fill('password@123');
  await page.waitForTimeout(9000);
  await page1.getByRole('button', { name: 'submit' }).click();
});